export const groceriesData = [
  {
    id: 1,
    name: "Audi",
    desc: "Audi A6 - All new collection of Audi A6",
    quantity: 3,
    total: 6500000,
  },
  {
    id: 2,
    name: "Mercedes",
    desc: "Mercedes - Maybach - ultra luxury",
    quantity: 3,
    total: 22500000,
  },
  {
    id: 3,
    name: "Rolls Royce",
    desc: "Rolls Royce - Phantom - ultra luxury and comfort",
    quantity: 3,
    total: 250000000,
  },
  {
    id: 4,
    name: "Lamborghini",
    desc: "Lamborghini Revuelto - all new latest collection of sports bike",
    quantity: 1,
    total: 50000000,
  },
  {
    id: 5,
    name: "Ferrari",
    desc: "Ferrari F8 Tributo - new luxury and sports",
    quantity: 3,
    total: 360000000,
  },
  {
    id: 6,
    name: "Porsche",
    desc: "Porsche Taycan Turbo S",
    quantity: 3,
    total: 34000000,
  },
  {
    id: 7,
    name: "Range Rover",
    desc: "Range Rover - Velar",
    quantity: 3,
    total: 12000000,
  },
  {
    id: 8,
    name: "Range Rover",
    desc: "Range Rover - Discovery",
    quantity: 1,
    total: 28000000,
  },
  {
    id: 9,
    name: "Tesla",
    desc: "Tesla Model S - Electric luxury sedan",
    quantity: 2,
    total: 90000000,
  },
  {
    id: 10,
    name: "BMW",
    desc: "BMW M5 - High-performance sports sedan",
    quantity: 2,
    total: 7000000,
  },
  {
    id: 11,
    name: "Jaguar",
    desc: "Jaguar F-Type - Elegant and powerful sports car",
    quantity: 2,
    total: 55000000,
  },
  {
    id: 12,
    name: "Maserati",
    desc: "Maserati Quattroporte - Italian luxury sedan",
    quantity: 1,
    total: 15000000,
  },
  {
    id: 13,
    name: "Bugatti",
    desc: "Bugatti Chiron - World's fastest and most luxurious car",
    quantity: 1,
    total: 300000000,
  },
  {
    id: 14,
    name: "McLaren",
    desc: "McLaren 720S - Super series sports car",
    quantity: 2,
    total: 28000000,
  },
  {
    id: 15,
    name: "Lexus",
    desc: "Lexus LC 500 - Luxury coupe with a performance edge",
    quantity: 2,
    total: 9500000,
  },
  {
    id: 16,
    name: "Alfa Romeo",
    desc: "Alfa Romeo Giulia Quadrifoglio - Italian performance sedan",
    quantity: 2,
    total: 45000000,
  },
  {
    id: 17,
    name: "Aston Martin",
    desc: "Aston Martin DBS Superleggera - British grand tourer",
    quantity: 1,
    total: 32000000,
  },
  {
    id: 18,
    name: "Nissan",
    desc: "Nissan GT-R - Japanese high-performance sports car",
    quantity: 2,
    total: 12000000,
  },
  {
    id: 19,
    name: "Infiniti",
    desc: "Infiniti QX80 - Luxury SUV with advanced technology",
    quantity: 3,
    total: 7500000,
  },
  {
    id: 20,
    name: "Volvo",
    desc: "Volvo XC90 - Scandinavian luxury SUV",
    quantity: 3,
    total: 6500000,
  },
  {
    id: 21,
    name: "Range Rover",
    desc: "Range Rover - Sport",
    quantity: 2,
    total: 30000000,
  },
  {
    id: 22,
    name: "Ferrari",
    desc: "Ferrari 812 Superfast - V12 grand tourer",
    quantity: 1,
    total: 450000000,
  },
  {
    id: 23,
    name: "Porsche",
    desc: "Porsche 911 Turbo S - Iconic sports car",
    quantity: 2,
    total: 40000000,
  },
  {
    id: 24,
    name: "Tesla",
    desc: "Tesla Model X - Electric SUV",
    quantity: 2,
    total: 100000000,
  },
  {
    id: 25,
    name: "BMW",
    desc: "BMW X5 - Luxury SUV with cutting-edge technology",
    quantity: 3,
    total: 11000000,
  },
  {
    id: 26,
    name: "Audi",
    desc: "Audi Q7 - Premium SUV with advanced features",
    quantity: 3,
    total: 8500000,
  },
  {
    id: 27,
    name: "Mercedes",
    desc: "Mercedes-Benz GLE - Stylish and powerful SUV",
    quantity: 3,
    total: 12000000,
  },
  {
    id: 28,
    name: "Lamborghini",
    desc: "Lamborghini Urus - High-performance luxury SUV",
    quantity: 2,
    total: 35000000,
  },
  {
    id: 29,
    name: "Jaguar",
    desc: "Jaguar I-PACE - Electric SUV with a sleek design",
    quantity: 2,
    total: 8000000,
  },
  {
    id: 30,
    name: "Maserati",
    desc: "Maserati Levante - Italian luxury SUV",
    quantity: 1,
    total: 14000000,
  },
  {
    id: 31,
    name: "Bugatti",
    desc: "Bugatti Veyron - Legendary hypercar",
    quantity: 1,
    total: 250000000,
  },
  {
    id: 32,
    name: "McLaren",
    desc: "McLaren P1 - Hybrid hypercar with stunning performance",
    quantity: 1,
    total: 32000000,
  },
  {
    id: 33,
    name: "Lexus",
    desc: "Lexus RX 350 - Luxury crossover with advanced safety features",
    quantity: 3,
    total: 8500000,
  },
  {
    id: 34,
    name: "Alfa Romeo",
    desc: "Alfa Romeo Stelvio - Italian luxury crossover",
    quantity: 2,
    total: 40000000,
  },
  {
    id: 35,
    name: "Aston Martin",
    desc: "Aston Martin Vantage - Exquisite sports car",
    quantity: 1,
    total: 28000000,
  },
  {
    id: 36,
    name: "Nissan",
    desc: "Nissan Armada - Full-size SUV with a bold presence",
    quantity: 2,
    total: 13000000,
  },
  {
    id: 37,
    name: "Infiniti",
    desc: "Infiniti Q50 - Luxury sports sedan",
    quantity: 2,
    total: 7500000,
  },
  {
    id: 38,
    name: "Volvo",
    desc: "Volvo S90 - Elegant and safe luxury sedan",
    quantity: 3,
    total: 9000000,
  },
  {
    id: 39,
    name: "Range Rover",
    desc: "Range Rover - Evoque",
    quantity: 2,
    total: 18000000,
  },
  {
    id: 40,
    name: "Ferrari",
    desc: "Ferrari Portofino - Grand touring convertible",
    quantity: 1,
    total: 380000000,
  },
  {
    id: 41,
    name: "Porsche",
    desc: "Porsche Panamera - Luxury performance sedan",
    quantity: 2,
    total: 35000000,
  },
  {
    id: 42,
    name: "Tesla",
    desc: "Tesla Model 3 - Electric sedan with cutting-edge technology",
    quantity: 3,
    total: 50000000,
  },
  {
    id: 43,
    name: "BMW",
    desc: "BMW X7 - Premium SUV with spacious interiors",
    quantity: 1,
    total: 16000000,
  },
  {
    id: 44,
    name: "Audi",
    desc: "Audi Q5 - Compact luxury SUV with advanced features",
    quantity: 3,
    total: 9500000,
  },
  {
    id: 45,
    name: "Mercedes",
    desc: "Mercedes-AMG GT - Performance sports car",
    quantity: 1,
    total: 30000000,
  },
  {
    id: 46,
    name: "Lamborghini",
    desc: "Lamborghini Aventador - Iconic V12 supercar",
    quantity: 1,
    total: 55000000,
  },
  {
    id: 47,
    name: "Jaguar",
    desc: "Jaguar XF - Luxury sedan with a dynamic design",
    quantity: 2,
    total: 11000000,
  },
  {
    id: 48,
    name: "Maserati",
    desc: "Maserati Ghibli - Italian sports sedan",
    quantity: 2,
    total: 32000000,
  },
  {
    id: 49,
    name: "Bugatti",
    desc: "Bugatti La Voiture Noire - The most expensive car in the world",
    quantity: 1,
    total: 500000000,
  },
  {
    id: 50,
    name: "McLaren",
    desc: "McLaren 570S - Sports series coupe",
    quantity: 2,
    total: 24000000,
  },
];
